// components/sidebar.tsx
import { Home, FolderOpen, AlertTriangle, Shield, Settings } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { cn } from '@/lib/utils'
import { Separator } from '@/components/ui/separator'
import { AIStatus } from '@/components/ai-status'
import { SidebarHeader } from '@/components/sidebar-header'

interface SidebarProps {
  className?: string
}

const menuItems = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    icon: Home,
  },
  {
    title: 'My ROPA',
    href: '/ropa',
    icon: FolderOpen,
  },
  {
    title: 'Risk Assessment',
    href: '/risk',
    icon: AlertTriangle,
  },
  {
    title: 'Breach Monitor',
    href: '/breach',
    icon: Shield,
  },
]

const adminItems = [
  {
    title: 'Administration',
    href: '/admin',
    icon: Settings,
  },
]

export function Sidebar({ className }: SidebarProps) {
  return (
    <div className={cn('flex flex-col min-h-screen border-r bg-slate-50', className)}>
      {/* Main Content */}
      <div className="space-y-4 py-4 flex-1">
        <div className="px-3 py-2">
          <SidebarHeader />
          <Separator className="my-4" />
          <div className="space-y-1">
            {menuItems.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-slate-700 transition-all hover:bg-slate-200 hover:text-slate-900"
              >
                <item.icon className="h-4 w-4" />
                <span className="text-sm font-medium">{item.title}</span>
              </Link>
            ))}
          </div>
          <Separator className="my-4" />
          <div className="space-y-1">
            {adminItems.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-slate-700 transition-all hover:bg-slate-200 hover:text-slate-900"
              >
                <item.icon className="h-4 w-4" />
                <span className="text-sm font-medium">{item.title}</span>
              </Link>
            ))}
          </div>
        </div>
      </div>

      {/* AI Status Footer with App Name */}
      <div className="border-t bg-white p-4">
        <div className="text-xs font-medium text-slate-600 mb-3">AI Status</div>
        <AIStatus />
        <Separator className="my-3" />
        <div className="flex flex-col items-center text-center py-2 gap-2">
          <Image
            src="/tanod-logo.svg"
            alt="TANOD Logo"
            width={32}
            height={32}
          />
          <div>
            <p className="text-xs font-semibold text-slate-700">TANOD</p>
            <p className="text-xs text-slate-500">DPO Compliance Platform</p>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/lib/components/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import {
    LayoutDashboard,
    FolderLock,
    ShieldAlert,
    Clock,
    UserCheck,
    FileText,
    Settings,
    Shield,
    HardDrive
  } from 'lucide-svelte';

  let currentPath = $derived($page.url.pathname);

  const navigation = [
    {
      group: 'Core Compliance',
      items: [
        { name: 'Dashboard', href: '/', icon: LayoutDashboard },
        { name: 'ROPA Registry', href: '/ropa', icon: FolderLock },
        { name: 'PIA 4×4 Matrix', href: '/pia', icon: ShieldAlert },
      ]
    },
    {
      group: 'Regulatory Enforcement',
      items: [
        { name: '72-Hour Breach Monitor', href: '/incidents', icon: Clock },
        { name: 'DSR Rights Helpdesk', href: '/dsr', icon: UserCheck },
        { name: 'DPO Directives & Memos', href: '/memos', icon: FileText },
      ]
    },
    {
      group: 'Administration',
      items: [
        { name: 'Entity & Governance', href: '/settings', icon: Settings },
      ]
    }
  ];
</script>

<aside class="w-64 bg-slate-900 border-r border-slate-800 flex flex-col h-screen select-none">
  <!-- Brand / Header -->
  <div class="h-16 flex items-center gap-3 px-5 border-b border-slate-800 bg-slate-950/60">
    <div class="h-9 w-9 rounded-lg bg-slate-800 border border-amber-500/30 flex items-center justify-center p-1 shadow-sm">
      <img src="/favicon.svg" alt="TANOD Shield" class="h-full w-full object-contain" />
    </div>
    <div class="flex flex-col min-w-0">
      <span class="text-sm font-bold tracking-wider text-slate-100 uppercase flex items-center gap-1.5">
        TANOD
        <span class="text-[9px] px-1.5 py-0.5 rounded font-mono font-medium bg-amber-500/10 text-amber-400 border border-amber-500/20">RA 10173</span>
      </span>
      <span class="text-[11px] text-slate-400 truncate">Philippine DPO Workspace</span>
    </div>
  </div>

  <!-- Navigation Links -->
  <nav class="flex-1 overflow-y-auto px-3 py-4 space-y-6">
    {#each navigation as section}
      <div>
        <h3 class="px-3 text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-2 font-mono">
          {section.group}
        </h3>
        <div class="space-y-1">
          {#each section.items as item}
            {@const isActive = currentPath === item.href || (item.href !== '/' && currentPath.startsWith(item.href))}
            <a
              href={item.href}
              class="flex items-center gap-3 px-3 py-2 rounded-md text-xs font-medium transition-colors {
                isActive 
                  ? 'bg-amber-500/15 text-amber-300 font-semibold border border-amber-500/30' 
                  : 'text-slate-300 hover:text-slate-100 hover:bg-slate-800/60'
              }"
            >
              <item.icon class="h-4 w-4 shrink-0 {isActive ? 'text-amber-400' : 'text-slate-400'}" />
              <span>{item.name}</span>
            </a>
          {/each}
        </div>
      </div>
    {/each}
  </nav>

  <!-- Offline Sovereignty Status Banner -->
  <div class="p-3 m-3 rounded-lg border border-slate-800 bg-slate-950/80">
    <div class="flex items-center gap-2 text-xs font-medium text-slate-300 mb-1">
      <HardDrive class="h-3.5 w-3.5 text-emerald-400" />
      <span>Local Encrypted DB</span>
    </div>
    <div class="flex items-center justify-between text-[11px] text-slate-400">
      <span>Storage</span>
      <span class="font-mono text-[10px] text-emerald-400 bg-emerald-950/50 px-1.5 py-0.5 rounded border border-emerald-800/40">100% Offline</span>
    </div>
  </div>
</aside>
